# Generated by Django 3.2.3 on 2021-06-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('BenId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('RelToUser', models.TextField()),
                ('Age', models.IntegerField()),
                ('Gender', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticCentre',
            fields=[
                ('CentreId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=25)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=25)),
                ('patient_count_per_day', models.IntegerField()),
                ('Consultation_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('Hospital_name', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Gen_Beds', models.IntegerField()),
                ('Bed_vent', models.IntegerField()),
                ('Gen_Bed_price', models.IntegerField()),
                ('Bed_Vent_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('TestId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=25)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TestsOffered',
            fields=[
                ('TOId', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('TestsPerDay', models.IntegerField()),
                ('CentreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.diagnosticcentre')),
                ('TestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.tests')),
            ],
        ),
        migrations.CreateModel(
            name='SlotBookAndReport',
            fields=[
                ('SlotId', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfTest', models.DateField()),
                ('report', models.FileField(upload_to='xrays/')),
                ('status', models.BooleanField()),
                ('BeneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.beneficiary')),
                ('TestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.testsoffered')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorConsult',
            fields=[
                ('Opid', models.AutoField(primary_key=True, serialize=False)),
                ('ConsultDate', models.DateField()),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.doctor')),
                ('slotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.slotbookandreport')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Hospital_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.hospital'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.user'),
        ),
        migrations.CreateModel(
            name='BedBook',
            fields=[
                ('BedBookId', models.AutoField(primary_key=True, serialize=False)),
                ('TypeOfBed', models.TextField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Hospital_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.hospital')),
                ('slotId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedApp.slotbookandreport')),
            ],
        ),
    ]
