# Generated by Django 3.2.3 on 2021-07-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedApp', '0002_alter_testsoffered_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbookandreport',
            name='report',
            field=models.ImageField(upload_to='xrays/'),
        ),
    ]
